const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole,ResourceLoader}=require('jsdom');
const APP=path.resolve(__dirname,'..');
const resolveFile=file=>file.startsWith('fix/')?path.join(APP,file.slice(4)):file;
let results=[];
class LocalLoader extends ResourceLoader{fetch(url){const u=new URL(url);let p;if(u.hostname!=='1kuli1.github.io')return null;for(const [repo,root]of [['dX-START',APP],['DX-Academy','fix-other/DX-Academy'],['dx-os','fix-other/dx-os'],['dx-system','fix-other/dx-system']])if(u.pathname.startsWith('/'+repo+'/'))p=path.join(root,decodeURIComponent(u.pathname.slice(repo.length+2)));if(p&&fs.existsSync(p))return Promise.resolve(fs.readFileSync(p));return null;}}
function open(file,seed={}){let errors=[],alerts=[],locks=Promise.resolve(),downloads=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!/Not implemented:.*(HTMLCanvasElement|navigation|window.open)/.test(e.message))errors.push(e.message)});const repo=file.startsWith('fix/')?'dX-START':file.split('/')[1],relative=file.startsWith('fix/')?file.slice(4):file.split('/').slice(2).join('/');const dom=new JSDOM(fs.readFileSync(resolveFile(file),'utf8'),{url:'https://1kuli1.github.io/'+repo+'/'+relative,runScripts:'dangerously',resources:new LocalLoader(),virtualConsole:vc,beforeParse(w){
 for(const[k,v]of Object.entries(seed))w.localStorage.setItem(k,v);
 w.alert=m=>alerts.push(String(m));w.confirm=()=>true;w.open=()=>{};
 Object.defineProperty(w.navigator,'locks',{value:{request:(name,fn)=>{const run=locks.then(fn);locks=run.catch(()=>{});return run;}}});
 w.URL.createObjectURL=b=>{downloads.push(b);return 'blob:test'};w.URL.revokeObjectURL=()=>{};
 w.HTMLMediaElement.prototype.pause=function(){};w.HTMLMediaElement.prototype.play=function(){return Promise.resolve()};
 w.fetch=async()=>({ok:true,json:async()=>[],text:async()=>''});
 }});return {dom,w:dom.window,errors,alerts,downloads,wait:()=>new Promise(r=>setTimeout(r,50))};}
async function test(name,fn){try{await fn();results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',error:e.stack});process.exitCode=1;}}
async function withPage(file,seed,fn){const p=open(file,seed);try{await p.wait();await fn(p);}finally{p.w.close()}}
(async()=>{
await test('All main pages load in DOM with local scripts',async()=>{const files=[];function walk(d){for(const f of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,f.name);if(f.isDirectory()&&f.name!=='node_modules')walk(p);else if(p.endsWith('.html'))files.push('fix/'+path.relative(APP,p))}}walk(APP);for(const f of files)await withPage(f,{},async p=>assert.deepEqual(p.errors,[],f+': '+p.errors));});
await test('Main corrupt store does not export empty backup',()=>withPage('fix/index.html',{dxLogs:'{broken'},async p=>{p.w.exportJSON();assert.equal(p.downloads.length,0);assert.equal(p.w.localStorage.getItem('dxLogs'),'{broken');assert(p.alerts.length)}));
await test('Main restore saves corrupt original and restores fresh file',()=>withPage('fix/index.html',{dxLogs:'{broken'},async p=>{assert.equal(await p.w.dxRestoreLogs([{_id:'restored',station:'Test',freq:1008}]),true);assert.equal(p.w.getLogs()[0].station,'Test');const keys=Object.keys(p.w.localStorage).filter(k=>k.startsWith('dxLogsRecovery-'));assert.equal(keys.length,1);assert.equal(p.w.localStorage.getItem(keys[0]),'{broken')}));
await test('Main recovery quota failure preserves original',()=>withPage('fix/index.html',{dxLogs:'{broken'},async p=>{const proto=Object.getPrototypeOf(p.w.localStorage),old=proto.setItem;proto.setItem=function(){throw Error('QuotaExceededError')};try{assert.equal(await p.w.dxRestoreLogs([{station:'Test'}]),false);assert.equal(p.w.localStorage.getItem('dxLogs'),'{broken')}finally{proto.setItem=old}}));
await test('Deletion tracks ID when another tab inserts before selected row',()=>withPage('fix/index.html',{dxLogs:JSON.stringify([{_id:'a',station:'A',date:'2026-10-09',time:'20:00',freq:'1008'}])},async p=>{p.w.openProfile(0);p.w.localStorage.setItem('dxLogs',JSON.stringify([{_id:'b',station:'B'},{_id:'a',station:'A',date:'2026-10-09',time:'20:00',freq:'1008'}]));await p.w.deleteSelected();assert.deepEqual(Array.from(p.w.getLogs(),x=>x._id),['b']);assert(p.w.getLogRecords().find(x=>x._id==='a')._deletedAt)}));
await test('Two concurrent saves preserve both new observations',()=>withPage('fix/index.html',{},async p=>{await Promise.all([p.w.setLogs([{_id:'a',station:'A'}]),p.w.setLogs([{_id:'b',station:'B'}])]);assert.equal(p.w.getLogs().length,2)}));
await test('JSON export and import into empty logbook roundtrip',()=>withPage('fix/index.html',{},async p=>{const x=[{_id:'a',date:'2026-10-09',freq:1008,station:'A',txHistory:'History',placeHistory:'Town'}];await p.w.setLogs(x);const before=JSON.stringify(p.w.getLogRecords());p.w.localStorage.removeItem('dxLogs');const input=p.w.document.getElementById('dxJsonImport');Object.defineProperty(input,'files',{configurable:true,value:[new p.w.File([before],'backup.json',{type:'application/json'})]});p.w.importJSON({target:input});await new Promise(r=>setTimeout(r,100));assert.equal(p.w.getLogs().length,1);assert.equal(p.w.getLogs()[0].txHistory,'History');assert.equal(p.w.getLogs()[0].freq,'1008')}));
await test('Older import cannot revive deleted observation',()=>withPage('fix/index.html',{},async p=>{const old={_id:'a',station:'A',_updatedAt:'2026-10-09T19:00:00Z'};await p.w.setLogs([{...old,_deletedAt:'2026-10-09T20:00:00Z',_updatedAt:'2026-10-09T20:00:00Z'}]);await p.w.setLogs([old]);assert.equal(p.w.getLogs().length,0)}));
await test('Excel unit/history/mode fidelity',()=>withPage('fix/index.html',{},async p=>{const rows=[['Datum','UTC','Frekvens','Frekvensenhet','Band','Station','Mode','Historien bakom sändaren/stationen','Historien bakom orten/sändarplatsen'],['2026-10-09','20:00','14.074','MHz','Amatörradio','SM1ABC','FT8','Sender','Town']];const x=p.w.mapExcelRows(rows,'SSB')[0];assert.equal(x.frequencyUnit,'MHz');assert.equal(x.txHistory,'Sender');assert.equal(x.placeHistory,'Town');assert.notEqual(p.w.logKey(x),p.w.logKey({...x,mode:'CW'}));rows[1][3]='';assert.throws(()=>p.w.mapExcelRows(rows,'SSB'),/frekvensenhet/)}));
await test('FM to MW changes unit and valid coordinates exclude null/out of range',()=>withPage('fix/index.html',{},async p=>{const d=p.w.document;d.getElementById('band').value='FM';p.w.updateExtraFields();assert.equal(d.getElementById('frequencyUnit').value,'MHz');d.getElementById('band').value='MW';p.w.updateExtraFields();assert.equal(d.getElementById('frequencyUnit').value,'kHz');assert.equal(p.w.dxCoordinates(null,null),null);assert.equal(p.w.dxCoordinates(200,500),null);assert(p.w.dxCoordinates(59,13));assert.equal(p.w.dxCoordinates('',13),null)}));
await test('Catastrophe corrupt save cannot overwrite original',()=>withPage('fix/katastrof-dx.html',{dxKatastrofLogV1:'{broken'},async p=>{const d=p.w.document;d.getElementById('event').value='Test';d.getElementById('area').value='Sweden';await p.w.saveLog();assert.equal(p.w.localStorage.getItem('dxKatastrofLogV1'),'{broken');assert(d.getElementById('logStatus').textContent.includes('Originaldata'))}));
await test('Catastrophe restore and normal saving',()=>withPage('fix/katastrof-dx.html',{},async p=>{const input=p.w.document.getElementById('catBackup');await p.w.importBackup({target:{files:[{text:async()=>JSON.stringify([{id:1,event:'Recovered',area:'Sweden'}])}],value:'x'}});assert.equal(p.w.load().length,1);p.w.document.getElementById('event').value='New';p.w.document.getElementById('area').value='Sweden';await p.w.saveLog();assert.equal(p.w.load().length,2);await p.w.del('1');assert.equal(p.w.load().length,1)}));
await test('Academy AI fields are real DOM elements',()=>withPage('fix/academy/nyborgare/ai_niva_1.html',{},async p=>{assert(p.w.document.getElementById('utc'));p.w.utcNow();assert(p.w.document.getElementById('utc').value.includes('UTC'));assert(p.w.document.querySelector('meta[name="viewport"]'))}));
await test('Lesson preserves frequency and displays HTML as text',()=>withPage('fix/academy/nyborgare/dx_logg_v1_utc_knapp (1).html',{},async p=>{assert.equal(p.w.justeraFrekvens('960').justerad,960);assert.equal(p.w.analyseraLogg({frekvens:'1332'}).säkerhet,'Ej bedömd');const d=p.w.document;d.getElementById('frekvens').value='960';d.getElementById('innehall').value='<img src=x onerror=void(0)>';p.w.analyseraOchSpara();assert.equal(d.querySelectorAll('#loggLista img').length,0);assert(d.getElementById('loggLista').textContent.includes('<img'))}));
await test('Live demo can stop before recording without error',()=>withPage('fix/academy/live-analys-demo.html',{},async p=>{p.w.stopRecording();assert.deepEqual(p.errors,[])}));
await test('Every main tool view opens without runtime error',()=>withPage('fix/index.html',{},async p=>{for(const tool of ['receivers','log','book','sync','map','cw','digital','audio','profile','special']){p.w.history.replaceState(null,'','?tool='+tool);p.w.dxApplyToolWindow();await new Promise(r=>setTimeout(r,100));assert.equal(p.w.document.getElementById(tool).style.display,'block');}assert.deepEqual(p.errors,[])}));
await test('CSV text cannot become an Excel formula and SWL has one unit',()=>withPage('fix/index.html',{dxLogs:JSON.stringify([{_id:'a',station:'=1+1',freq:'1008'}])},async p=>{p.w.exportCSV();const blob=p.downloads.at(-1);const text=await new Promise((resolve,reject)=>{const r=new p.w.FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsText(blob)});assert(text.includes('"\'=1+1"'));assert(!p.w.dxMakeSWLReport({freq:'14.074 MHz',frequencyUnit:'MHz'}).includes('MHz MHz'))}));
await test('Microphone tracks stop for main recording and demo',async()=>{for(const file of ['fix/index.html','fix/academy/live-analys-demo.html'])await withPage(file,{},async p=>{let stopped=0;Object.defineProperty(p.w.navigator,'mediaDevices',{value:{getUserMedia:async()=>({getTracks:()=>[{stop:()=>stopped++}]})}});p.w.MediaRecorder=class{constructor(){this.state='inactive';this.mimeType='audio/webm'}start(){this.state='recording'}stop(){this.state='inactive';this.onstop?.()}};if(file==='fix/index.html'){await p.w.dxStartRecording();p.w.dxStopRecording()}else{await p.w.startRecording();p.w.stopRecording()}assert.equal(stopped,1)});});
await test('Satellite fields save, display, export and restore without leaking to other bands',()=>withPage('fix/index.html',{},async p=>{
 const w=p.w,d=w.document,set=(id,v)=>d.getElementById(id).value=v;
 set('band','Satellit');w.updateExtraFields();assert.equal(d.getElementById('satelliteFields').hidden,false);assert.equal(d.querySelector('label[for="freq"]').textContent,'Nedlänksfrekvens');
 const values={satelliteName:'QO-100 <test>',satelliteCallsign:'SM1ABC',satellitePassStart:'2026-10-10T23:58',satellitePassEnd:'2026-10-11T00:08'};
 for(const [k,v]of Object.entries(values))set(k,v);set('freq','10489.7');set('frequencyUnit','MHz');set('date','2026-10-10');set('time','23:59');await w.saveLog();
 assert.equal(w.getLogs().length,1);const log=w.getLogs()[0];for(const [k,v]of Object.entries(values))assert.equal(log[k],v);assert.equal(log.station,'SM1ABC');assert.equal(log.frequencyUnit,'MHz');assert.equal(d.getElementById('satelliteName').value,'');
 w.openProfile(0);assert(d.getElementById('pSatelliteDetails').textContent.includes('QO-100 <test>'));assert.equal(d.querySelectorAll('#pSatelliteDetails test').length,0);
 w.exportCSV();const csv=await new Promise(r=>{const f=new w.FileReader();f.onload=()=>r(f.result);f.readAsText(p.downloads.at(-1));});assert(csv.includes('satellitePassEnd'));assert(csv.includes('2026-10-11T00:08'));
 const restored=w.dxNormalizeLog(JSON.parse(JSON.stringify(log)));await w.dxRestoreLogs([restored]);for(const [k,v]of Object.entries(values))assert.equal(w.getLogs()[0][k],v);
 const rows=[['Datum','Frekvens','Station','Frekvensenhet','Band',...Object.keys(values)],['2026-10-10','10489.7','SM1ABC','MHz','Satellit',...Object.values(values)]];const excel=w.mapExcelRows(rows,'Satellit')[0];for(const [k,v]of Object.entries(values))assert.equal(excel[k],v);
 set('satellitePassStart','2026-10-11T00:08');set('satellitePassEnd','2026-10-10T23:58');set('freq','145.8');await w.saveLog();assert.equal(w.getLogs().length,1);assert(p.alerts.at(-1).includes('Passagens slut'));
 set('band','MW');w.updateExtraFields();assert(d.getElementById('satelliteFields').hidden);assert.equal(d.querySelector('label[for="freq"]').textContent,'Frekvens');set('station','Other');set('freq','1008');await w.saveLog();assert.equal(w.getLogs()[0].satelliteName,'');
}));

console.log(JSON.stringify(results,null,2));
})();